runtime: python
env: flex
entrypoint: gunicorn -b :$PORT run:app

runtime_config:
  operating_system: ubuntu22

env_variables:
  SQLALCHEMY_DATABASE_URI: "postgresql://almaz:jsonmarket2024!@/postgres?host=/cloudsql/jsonmarket:us-central1:jsonmarket-db"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: "jsonmarket:us-central1:jsonmarket-db"
